version: "3.4"

services:
  crisp_homework:
    build:
      context: .
    command: src/transformer.py  --config src/config.yml --input input_files/sample_input.csv --success output_files/success.csv --failure output_files/failure.csv
    volumes:
      - .:/crispy_project
