---
 input-fields:
   - Order Number
   - Year
   - Month
   - Day
   - Product Number
   - Product Name
   - Count
   - Extra Col1
   - Extra Col2
   - Empty Column
 output-fields:
   OrderID:
     Type: integer
     Transform: "${Order Number}"
   OrderDate:
     Type: text
     Transform: "kg"
   ProductId:
     Type: text
     Transform: "kg"
   ProductName:
     Type: text
     Transform: "kg"
   Quantity:
     Type: real
     Transform: "kg"
   Unit:
     Type: text
     Transform: "kg"
