---
 input-fields:
   Order Number:
     Type: INTEGER
   Year:
     Type: INTEGER
   Month:
     Type: INTEGER
   Day:
     Type: INTEGER
   Product Number:
     Type: STRING
   Product Name:
     Type: STRING
   Count:
     Type: STRING
   Extra Col1:
     Type: STRING
   Extra Col2:
     Type: STRING
   Empty Column:
     Type: STRING

 output-fields:
   OrderID:
     Type: INTEGER
     Transform: "'${Order Number}'"
   OrderDate:
     Type: STRING
     Transform: "datetime.datetime(year=${Year}, month=${Month}, day=${Day}).strftime('%Y-%m-%d')"
   ProductId:
     Type: STRING
     Transform: "'${Product Number}'"
   ProductName:
     Type: STRING
     Transform: "'${Product Name}'.title()"
   Quantity:
     Type: FLOAT
     Transform: "float('${Count}'.replace(',', ''))"
   Unit:
     Type: STRING
     Transform: "'kg'"
