---
 input-fields:
   - Order Number
   - Year
   - Month
   - Day
   - Product Number
   - Product Name
   - Count
   - Extra Col1
   - Extra Col2
   - Empty Column
 output-fields:
   OrderID:
     Type: INTEGER
     Transform: "int('${Order Number}')"
   OrderDate:
     Type: DATE
     Transform: "datetime.strptime('${Day}/${Month}/${Year}', '%d/%m/%Y')"
   ProductId:
     Type: STRING
     Transform: "str('${Product Number}')"
   ProductName:
     Type: STRING
     Transform: "'${Product Name}'.title()"
   Quantity:
     Type: FLOAT
     Transform: "float('${Count}'.replace(',', ''))"
   Unit:
     Type: STRING
     Transform: "'kg'"
