---
 input-fields:
   Order Number:
     Type: INTEGER
   Year:
     Type: INTEGER
   Month:
     Type: INTEGER
   Day:
     Type: INTEGER
   Product Number:
     Type: STRING
   Product Name:
     Type: STRING
   Count:
     Type: STRING
   Extra Col1:
     Type: STRING
   Extra Col2:
     Type: STRING
   Empty Column:
     Type: STRING
